[theme]
base = "light"
primaryColor = "#EF4E23"
backgroundColor = "#F8F7F2"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#111111"
font = "sans serif"

[theme.sidebar]
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F1EFED"
primaryColor = "#EF4E23"
textColor = "#111111"
